apiVersion: apps/v1
kind: Deployment
metadata:
  name: ergosense-api
  namespace: ergosense
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: api
          imagePullPolicy: IfNotPresent
          env:
            - name: PGHOST
              value: ergosense-postgres
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: ergosense
            - name: PGUSER
              value: ergosense
            - name: REDIS_ENABLED
              value: "true"
            - name: REDIS_URL
              value: redis://ergosense-redis:6379
            - name: STORAGE_DRIVER
              value: database
            - name: CORS_ORIGINS
              value: "*"
