apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ergosense
resources:
  - namespace.yaml
  - configmap-api.yaml
  - secret-api.yaml
  - deployment-api.yaml
  - service-api.yaml
  - deployment-web.yaml
  - service-web.yaml
  - ingress.yaml
  - hpa-api.yaml
  - pvc-postgres.yaml
  - pvc-redis.yaml
commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: ergosense
