apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ergosense-redis-pvc
  namespace: ergosense
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
