apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ergosense-postgres-pvc
  namespace: ergosense
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
